// AUTO-GENERATED by scripts/generate-media-index.mjs — do not edit by hand.
// Personal index of every usable photo/video from the raw phone dump,
// compressed into public/gallery and public/videos. Re-run the script
// after optimize-media.mjs to refresh this file.

export type MediaDay = '22 luglio 2026' | '23 luglio 2026' | '24 luglio 2026' | 'Ricordi extra'

export type MediaItem = {
  file: string
  day: MediaDay
}

export const galleryFullIndex: MediaItem[] = [
  {
    "file": "1784886022277.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022351.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022391.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022435.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022477.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022514.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022551.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022591.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022623.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022660.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022679.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022701.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022717.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022735.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022753.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022793.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022818.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022841.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022867.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022905.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022946.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022979.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886022998.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886023022.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886023041.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886023058.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886023076.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886023096.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886023116.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "1784886023132.jpg",
    "day": "Ricordi extra"
  },
  {
    "file": "IMG-20260722-WA0043.jpg",
    "day": "22 luglio 2026"
  },
  {
    "file": "IMG-20260722-WA0044.jpg",
    "day": "22 luglio 2026"
  },
  {
    "file": "IMG-20260722-WA0045.jpg",
    "day": "22 luglio 2026"
  },
  {
    "file": "IMG-20260723-WA0001.jpg",
    "day": "23 luglio 2026"
  },
  {
    "file": "IMG-20260723-WA0007.jpg",
    "day": "23 luglio 2026"
  },
  {
    "file": "IMG-20260723-WA0008.jpg",
    "day": "23 luglio 2026"
  },
  {
    "file": "IMG-20260723-WA0009.jpg",
    "day": "23 luglio 2026"
  },
  {
    "file": "IMG-20260723-WA0010.jpg",
    "day": "23 luglio 2026"
  },
  {
    "file": "IMG-20260723-WA0011.jpg",
    "day": "23 luglio 2026"
  },
  {
    "file": "IMG-20260723-WA0012.jpg",
    "day": "23 luglio 2026"
  },
  {
    "file": "IMG-20260723-WA0013.jpg",
    "day": "23 luglio 2026"
  },
  {
    "file": "IMG-20260723-WA0014.jpg",
    "day": "23 luglio 2026"
  },
  {
    "file": "IMG-20260723-WA0015.jpg",
    "day": "23 luglio 2026"
  },
  {
    "file": "IMG-20260723-WA0016.jpg",
    "day": "23 luglio 2026"
  },
  {
    "file": "IMG-20260723-WA0017.jpg",
    "day": "23 luglio 2026"
  },
  {
    "file": "IMG-20260723-WA0018.jpg",
    "day": "23 luglio 2026"
  },
  {
    "file": "IMG-20260723-WA0019.jpg",
    "day": "23 luglio 2026"
  },
  {
    "file": "IMG-20260723-WA0020.jpg",
    "day": "23 luglio 2026"
  },
  {
    "file": "IMG-20260723-WA0021.jpg",
    "day": "23 luglio 2026"
  },
  {
    "file": "IMG-20260723-WA0022.jpg",
    "day": "23 luglio 2026"
  },
  {
    "file": "IMG-20260723-WA0023.jpg",
    "day": "23 luglio 2026"
  },
  {
    "file": "IMG-20260723-WA0024.jpg",
    "day": "23 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0000.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0001.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0002.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0003.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0004.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0005.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0006.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0007.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0008.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0009.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0010.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0011.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0012.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0013.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0014.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0015.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0016.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0017.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0018.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0019.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0020.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0021.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0022.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0023.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0024.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0025.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0026.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0027.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0028.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0029.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0030.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0031.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0032.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0033.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0034.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0035.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0036.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0037.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0038.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0039.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0040.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0041.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0042.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0043.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0044.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0045.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0046.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0047.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0048.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0049.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0050.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0051.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0052.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0053.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0054.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0055.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0056.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0057.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0058.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0059.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0060.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0061.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0065.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0066.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0067.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0068.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0070.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0071.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0073.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0074.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0075.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0076.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0077.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0078.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0079.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0080.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0081.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0082.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0083.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0084.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0085.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0086.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0087.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0088.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0089.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0090.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0091.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0092.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0093.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0094.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0095.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0096.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0097.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0098.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0099.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0100.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0101.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0102.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0103.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0105.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0106.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0107.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0108.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0109.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0110.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0111.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0112.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0113.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0114.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0115.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0116.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0117.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0118.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0119.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0120.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0121.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0122.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0123.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0124.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0125.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0130.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0131.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0132.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0133.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0134.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0135.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0136.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0137.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0140.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0141.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0142.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0143.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0144.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0146.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0148.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0149.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0150.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0151.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0152.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0153.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0154.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0155.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0156.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0157.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0158.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0159.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0160.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0161.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0162.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0164.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0165.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0166.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0167.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0168.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0169.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0170.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0171.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0172.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0173.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0174.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0175.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0176.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0179.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0180.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0181.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0182.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0183.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0184.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0185.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0186.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0187.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0188.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0189.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0190.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0193.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0194.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0195.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0196.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0197.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0198.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0199.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0200.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0201.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0202.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0203.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0204.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0205.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0206.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0207.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0208.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0209.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0210.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0211.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0212.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0213.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0214.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0215.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0216.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0217.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0218.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0219.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0220.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0221.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0222.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0223.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0224.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0225.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0226.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0227.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0228.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0229.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0230.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0231.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0232.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0233.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0234.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0235.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0236.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0237.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0238.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0239.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0240.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0241.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0242.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0243.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0244.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0245.jpg",
    "day": "24 luglio 2026"
  },
  {
    "file": "IMG-20260724-WA0246.jpg",
    "day": "24 luglio 2026"
  }
]

export const videoIndex: MediaItem[] = [
  {
    "file": "VID-20260723-WA0002.mp4",
    "day": "23 luglio 2026"
  },
  {
    "file": "VID-20260724-WA0062.mp4",
    "day": "24 luglio 2026"
  },
  {
    "file": "VID-20260724-WA0063.mp4",
    "day": "24 luglio 2026"
  },
  {
    "file": "VID-20260724-WA0064.mp4",
    "day": "24 luglio 2026"
  },
  {
    "file": "VID-20260724-WA0069.mp4",
    "day": "24 luglio 2026"
  },
  {
    "file": "VID-20260724-WA0072.mp4",
    "day": "24 luglio 2026"
  },
  {
    "file": "VID-20260724-WA0104.mp4",
    "day": "24 luglio 2026"
  },
  {
    "file": "VID-20260724-WA0126.mp4",
    "day": "24 luglio 2026"
  },
  {
    "file": "VID-20260724-WA0127.mp4",
    "day": "24 luglio 2026"
  },
  {
    "file": "VID-20260724-WA0128.mp4",
    "day": "24 luglio 2026"
  },
  {
    "file": "VID-20260724-WA0129.mp4",
    "day": "24 luglio 2026"
  },
  {
    "file": "VID-20260724-WA0138.mp4",
    "day": "24 luglio 2026"
  },
  {
    "file": "VID-20260724-WA0139.mp4",
    "day": "24 luglio 2026"
  },
  {
    "file": "VID-20260724-WA0145.mp4",
    "day": "24 luglio 2026"
  },
  {
    "file": "VID-20260724-WA0147.mp4",
    "day": "24 luglio 2026"
  },
  {
    "file": "VID-20260724-WA0163.mp4",
    "day": "24 luglio 2026"
  },
  {
    "file": "VID-20260724-WA0177.mp4",
    "day": "24 luglio 2026"
  },
  {
    "file": "VID-20260724-WA0178.mp4",
    "day": "24 luglio 2026"
  },
  {
    "file": "VID_20260723_115847.mp4",
    "day": "23 luglio 2026"
  }
]
